### ISSUE TITLE
App.asar not working.

### ISSUE THREAD

**Issue by Apelsenya** [robiot/Digiexam-HackedVersion#3]
The app.asar  has been patched on the 13.3.0 version and I would like to know if there is a way to fix it, or do something about it.

**Comment by robiot** [comment]
Can you use the https://github.com/robiot/Digiexam-HackedVersion/releases/download/v1.0.0/app-13.0.3.zip ?

**Comment by Apelsenya** [comment]
Yeah, but I have already a new 13.3.0 version. Why should I download this? or should I delete 13.3.0 version?

**Comment by Apelsenya** [comment]
How can I use this: https://github.com/robiot/Digiexam-HackedVersion/releases/download/v1.0.0/app-13.0.3.zip ? Because when I start an exam, I just get a white screen! What should I do?

**Comment by robiot** [comment]
Thats weird. Well I have never had the oportunity to run this on a real exam so I havne't been able to test. Guess its a issue somewhere which I cant fix :\

**Comment by Sweaboy** [comment]
Did you fix it?

**Comment by Tigerfyy** [comment]
Hey, robiot. Would be really appreciated if you could look into the latest version see if it’s patched.  

I’m in need of this kinda bad for my last months in school already failed a test so having a second chance in 2 weeks.

best regards

**Comment by robiot** [comment]
> Hey, robiot. Would be really appreciated if you could look into the latest version see if it’s patched.  
> 
> 
> 
> I’m in need of this kinda bad for my last months in school already failed a test so having a second chance in 2 weeks.
> 
> 
> 
> best regards

Yeah, I got no clue of how to fix it since its hard, the code is heavily obfuscated and I cant test with a real test :(

**Comment by Tigerfyy** [comment]
Okay, going to try it out tomorrow on a test with13.0.30 and ur app.asar. I can update you what happens.

**Comment by robiot** [comment]
> Okay, going to try it out tomorrow on a test with13.0.30 and ur app.asar. I can update you what happens.

Perfect

**Comment by Tigerfyy** [comment]
Allt that happens is egen I launch the exam and promts me to close all application, I press yes and then DigiExam just terminated/crashes

**Comment by robiot** [comment]
> Allt that happens is egen I launch the exam and promts me to close all application, I press yes and then DigiExam just terminated/crashes

Hm, well I don't really know what I can do since I can't test it myself :\

**Comment by Kardanis** [comment]
Digiexam will shut down other activities correctly. It can still be opened in the virtual machine, but it will not be able to join the exam normally. After clicking "Start Exam", it will automatically shut down
